spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  cloud:
    compatibility-verifier:
      enabled: false

  application:
    name: activityservice
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: aiactivityfitness

server:
  port: 8082




kafka:
  topic:
    name: activity-events

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




